version: '3.8'
services:
  db:
      image: 'postgres:14.4'
      environment:
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      volumes:
        - db-data:/var/lib/postgresql/data
volumes:
  db-data: