version: '3.8'
services:
  db:
      image: 'postgres:14.4'
      environment:
        - POSTGRES_USER=${DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
        - POSTGRES_DB=${DATABASE_NAME}
      volumes:
        - db-data:/var/lib/postgresql/data
      ports:
      - ${DATABASE_PORT-5678}:5432
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin1234
    ports:
      - ${PG_ADMIN_PORT-5050}:80
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    logging:
      driver: none
volumes:
  db-data:
  pgadmin:
